### ISSUE TITLE
can't start core

### ISSUE THREAD

**Issue by debiansid** [qjebbs/sing-box#7]
### 操作系统

Android

### 系统版本

13

### 安装类型

sing-box 原始命令行程序

### 版本

<details>
```console
❯ ./sing-box version                                    sing-box version 1.4.0

Environment: go1.21.0 android/arm64
Tags: with_quic,with_gvisor,with_ech,with_utls,with_ech,with_clash_api,with_provider_loadbalance
Revision: 6d909772189743cc987e5e6bf2cd85db8cd22ce2
CGO: enabled
```
</details>

### 描述

启动脚本无法启动内核

### 重现方式

sing-box run -c config.json -D /somewhere

### 日志

<details>
```console
panic: runtime error: index out of range [0] with length 0

goroutine 18 [running, locked to thread]:
github.com/sagernet/sing-box/outbound.(*Selector).Start(0x40000d60e0)
	/home/runner/work/sing-box-sub/sing-box-sub/outbound/selector.go:78 +0x374
github.com/sagernet/sing-box.(*Box).startOutbounds(0x40000ac2c0)
	/home/runner/work/sing-box-sub/sing-box-sub/box_outbound.go:47 +0x524
github.com/sagernet/sing-box.(*Box).preStart(0x40000ac2c0)
	/home/runner/work/sing-box-sub/sing-box-sub/box.go:262 +0x3a0
github.com/sagernet/sing-box.(*Box).start(0x40000ac2c0)
	/home/runner/work/sing-box-sub/sing-box-sub/box.go:270 +0x28
github.com/sagernet/sing-box.(*Box).Start(0x40000ac2c0)
	/home/runner/work/sing-box-sub/sing-box-sub/box.go:222 +0x30
github.com/sagernet/sing-box/experimental/libbox.(*BoxService).Start(...)
	/home/runner/work/sing-box-sub/sing-box-sub/experimental/libbox/service.go:67
main.proxylibbox_BoxService_Start(0x942a8101?)
	/tmp/gomobile-work-707860006/src-android-arm64/gobind/go_libboxmain.go:48 +0x3c

```
</details>

**Comment by debiansid** [comment]
'''
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/sagernet/sing-box/outbound.(*Selector).Start(0x400032e000)
	github.com/sagernet/sing-box/outbound/selector.go:78 +0x380
github.com/sagernet/sing-box.(*Box).startOutbounds(0x4000316370)
	github.com/sagernet/sing-box/box_outbound.go:47 +0x570
github.com/sagernet/sing-box.(*Box).preStart(0x4000316370)
	github.com/sagernet/sing-box/box.go:258 +0x3c0
github.com/sagernet/sing-box.(*Box).start(0x4000316370)
	github.com/sagernet/sing-box/box.go:266 +0x28
github.com/sagernet/sing-box.(*Box).Start(0x4000316370)
	github.com/sagernet/sing-box/box.go:218 +0x30
main.create()
	github.com/sagernet/sing-box/cmd/sing-box/cmd_run.go:153 +0x344
main.run()
	github.com/sagernet/sing-box/cmd/sing-box/cmd_run.go:166 +0xc8
main.glob..func7(0x57b0f02b40?, {0x57af65aeae?, 0x2?, 0x2?})
	github.com/sagernet/sing-box/cmd/sing-box/cmd_run.go:28 +0x1c
github.com/spf13/cobra.(*Command).execute(0x57b0f02b40, {0x400008b580, 0x2, 0x2})
	github.com/spf13/cobra@v1.7.0/command.go:944 +0x5b0
github.com/spf13/cobra.(*Command).ExecuteC(0x57b0f02e20)
	github.com/spf13/cobra@v1.7.0/command.go:1068 +0x35c
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.7.0/command.go:992
main.main()
	github.com/sagernet/sing-box/cmd/sing-box/main.go:33 +0x28
'''

**Comment by debiansid** [comment]
config error
